name: Deploy to Stage
on:
  push:
    branches:
    - stage
jobs:
  frontend:
    name: Upload frontend to Amazon S3 Bucket
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Dependencies installation
      run: npm install
    - name: Build static files
      run: CI='' npm run build
#    - name: Create env file
#      run: |
#        touch build/.env
#        echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> build/.env
    - name: Clean S3 bucket from previous files with the AWS CLI
      run: aws s3 rm s3://rsm-cman-demo --recursive
    - name: Copy files to the bucket with the AWS CLI
      run: aws s3 sync build/ s3://rsm-cman-demo
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        SKIP_PREFLIGHT_CHECK: true
        PORT: 80
        NODE_ENV: stage

